### PR TITLE
Propagate the real redis error to the client instead of hiding it?

### PR DESCRIPTION
**Pull request by majikandy**
_Errors were hidden behind "Other(Server Error)"._

Raising this for discussion since I often experience forgetting to start Redis server and see Other (Server Error) and it feels like more information to the client call is better. (As long as no credentials or attack vectors exposed)

### CODE REVIEW

**Comment by craiga** [comment]
Would be good to see some before and after comparisons as part of this PR.

**Comment by majikandy** [comment]
Before
`Other (Server Error)`
After
`RedisIoError(Connection refused (os error 61))`

**Comment by majikandy** [comment]
@m-doughty decent idea

**Comment by majikandy** [comment]
added the var via make set-env too

**Pull request merged**
