### PR TITLE
Put CPD CDN profile in West Europe region

### PR DESCRIPTION
**Pull request by sgrowe**
You can't create CDN profiles in UK south sadly, which is where the rest of the non-prod infrastructure is located.

### CODE REVIEW

**Comment by StuartHarris** [comment]
Do you think we should move everything to West Europe then?

**Comment by StuartHarris** [comment]
Closed by mistake!

**Comment by sgrowe** [comment]
> Do you think we should move everything to West Europe then?

Yeah might as well, good shout

**Comment by rjkerrison** [comment]
oh, I just did #857 which solves this in a slightly different way. just gonna close this now

**Pull request closed without merging**
