### PR TITLE
Remove Not Applicable & Not Specified from A-Z lists.

### LINKED ISSUE #136: Not applicable is listed as an active substance
**Describe the bug**
Not applicable is listed as an active substance

**To Reproduce**
https://mhraproductsdev.z33.web.core.windows.net/?substance=NOT%20APPLICABLE
1) Go to MHRA website
2) Filter for 'n' under active substances
3) Click on Not applicable
4) Note 3 other active substances are listed here: 0.1% W/W POLYSORBATE 80 IN WATER FOR INJECTION (2 files)
METHADOSE DILUENT,METHADONE DILUENT (1 files)
STERILE DILUENT FOR HUMATROPE SOLVENT FOR SOLUTION FOR INJECTION (1 files)

**Expected behavior**
The 3 active substances listed on the 2nd level should be either on the first level under the correct letter/number, or under the 2nd level of the correct substance. 

**Screenshots**
Screenshot 2019-12-11 at 20 25 38

**Additional context**

### PR DESCRIPTION
**Pull request by m-doughty**
### Tickets

Resolves #136 

### Acceptance Criteria

- [x] Not Applicable and Not Specified do not appear in the A-Z list;
- [x] The documents can still be found in search.

### Pre-merge Checklist

- [ ] Branch test approved

### CODE REVIEW

**Comment by StuartHarris** [comment]
I wonder if this was actually the correct behaviour? They're all water-based products so probably it's correct to be "not applicable" or "not specified"

**Comment by m-doughty** [comment]
> I think we should check with the business that this was not actually desired/correct, before merging

Fair enough, who should I ask about this?

**Comment by craiga** [comment]
@m-doughty @KaylieGreen1607 I'm not sure what this is. Should it be closed or put on our board?

**Comment by TimboTambo** [comment]
The business has confirmed that the current behaviour is expected and can remain in the site so these changes are not required.

**Pull request closed without merging**
